// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TArray32 extends NonGrowableListView<T> {
  static const arraySize = 32;

  @internal
  List<T> get inner => _inner;
  final List<T> _inner;

  TArray32(this._inner)
      : assert(_inner.length == arraySize),
        super(_inner);

  TArray32.init(T fill) : this(List<T>.filled(arraySize, fill));
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<T>>
abstract class T implements RustOpaqueInterface {}
