[package]
name = "rust_lib_frostsnapp2"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
tokio-serial = {  version = "5.4.5" }
flutter_rust_bridge = "=2.8.0"
# frostsnap_core = { path = "../../frostsnap/frostsnap_core" }
# frostsnap_comms = { path = "../../frostsnap/frostsnap_comms" }
anyhow = "1"
tokio = { version = "1", features = ["time", "io-util"] }
futures  = "0.3"
log = "0.4"
async-stream = "0.3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
