// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `start`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `MAGICBYTES_RECV_UPSTREAM`

BigInt get magicBytesLen =>
    RustLib.instance.api.crateApiDeviceListMagicBytesLen();

Stream<List<String>> startUsbAndroid(
        {required FutureOr<List<String>> Function() listDevices,
        required FutureOr<Object> Function(String) openPort,
        required FutureOr<Uint8List> Function(Object) pollPort,
        required FutureOr<void> Function(Object, Uint8List) writePort}) =>
    RustLib.instance.api.crateApiDeviceListStartUsbAndroid(
        listDevices: listDevices,
        openPort: openPort,
        pollPort: pollPort,
        writePort: writePort);

Stream<List<String>> startUsbOrdinary() =>
    RustLib.instance.api.crateApiDeviceListStartUsbOrdinary();
