// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<AndroidUsb> startAndroidUsb(
        {required FutureOr<List<String>> Function() dartCallback}) =>
    RustLib.instance.api
        .crateApiDeviceListStartAndroidUsb(dartCallback: dartCallback);

Future<OrdinaryUsb> startOrdinaryUsb() =>
    RustLib.instance.api.crateApiDeviceListStartOrdinaryUsb();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AndroidUsb>>
abstract class AndroidUsb implements RustOpaqueInterface, PortLister {
  @override
  Stream<List<String>> subPorts();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OrdinaryUsb>>
abstract class OrdinaryUsb implements RustOpaqueInterface, PortLister {
  @override
  Stream<List<String>> subPorts();
}

abstract class PortLister {
  Stream<List<String>> subPorts();
}
