// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<List<String>> start({required UsbSerialImpl usbBackend}) =>
    RustLib.instance.api.crateApiDeviceListStart(usbBackend: usbBackend);

Future<UsbSerialImpl> usbAndroid(
        {required FutureOr<List<String>> Function() listDevices}) =>
    RustLib.instance.api.crateApiDeviceListUsbAndroid(listDevices: listDevices);

Future<UsbSerialImpl> usbOrdinary() =>
    RustLib.instance.api.crateApiDeviceListUsbOrdinary();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UsbSerialImpl>>
abstract class UsbSerialImpl implements RustOpaqueInterface {}
